### ISSUE TITLE
review package

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/statistical-software-review#6]
Submitting Author: Mark Padgham (@mpadge)
Repository:  https://github.com/mpadge/srr-demo
Version submitted: 0.0.0.9000
Editor: @mpadge
Reviewers: @noamross
Due date for @noamross: 2021-05-20
Archive: TBD
Version accepted: TBD

---

-   Paste the full DESCRIPTION file inside a code block below:

```
This package does nothing
```

## General Information

-   Who is the target audience and what are scientific applications of this package?

-   Paste your responses to our [*General Standard* **G1.1** here](https://ropenscilabs.github.io/statistical-software-review-book/standards.html#general-standards), describing whether your software is:

    - *The first implementation of a novel algorithm*; or
    - *The first implementation within **R** of an algorithm which has
      previously been implemented in other languages or contexts*; or
    - *An improvement on other implementations of similar algorithms in **R***.

    Please include hyperlinked references to all other relevant software.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

## Technical checks

Confirm each of the following by checking the box.

- [ ] I/we have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [ ] I/we have read the [*Statistical Software Peer Review* Guide for Authors](https://ropenscilabs.github.io/statistical-software-review-book/pkgdev.html).
- [ ] I/we have run [`autotest`](https://github.com/ropenscilabs/autotest) checks on the package, and ensured no tests fail.
- [ ] The [`srr_stats_pre_submit()` function](https://ropenscilabs.github.io/srr/reference/srr_stats_pre_submit.html) confirms this package may be submitted.

This package:

- [ ] does not violate the Terms of Service of any service it interacts with.
- [ ] has a CRAN and OSI accepted license.
- [ ] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).

## Publication options

- [ ] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

## Code of conduct

- [ ] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by mpadge** [comment]
@ropensci-review-bot help

**Comment by mpadge** [comment]
@ropensci-review-bot check package

**Comment by maelle** [comment]
@ropensci-review-bot check package

**Comment by maelle** [comment]
@ropensci-review-bot check package

**Comment by mpadge** [comment]
@ropensci-review-bot goodtoreview

**Comment by mpadge** [comment]
@ropensci-review-bot check package

**Comment by mpadge** [comment]
@ropensci-review-bot goodtoreview

**Comment by maelle** [comment]
@ropensci-review-bot check package

**Comment by mpadge** [comment]
@ropensci-review-bot goodtoreview

**Comment by mpadge** [comment]
@ropensci-review-bot check package

**Comment by mpadge** [comment]
## Checks for [demo (v0.0.0.9000)](https://github.com/mpadge/srr-demo)

git hash: [1e2f8c99](https://github.com/mpadge/srr-demo/tree/1e2f8c99f49ccd2285aa0f0f9bcb42a8c8625c09)

- :heavy_check_mark: Package uses 'roxygen2'
- :heavy_multiplication_x: Package does not have a 'contributing.md' file
- :heavy_check_mark: All functions have examples
- :heavy_check_mark: Package 'DESCRIPTION' has a URL field
- :heavy_multiplication_x: Package 'DESCRIPTION' does not have a BugReports field
- :heavy_multiplication_x: Package has no continuous integration checks

**Important:** All failing checks above must be addressed prior to proceeding

Package License: GPL-3



### Details

<details>
<summary>Click to see</summary>
<p>

### Package Statistics

<details>
<summary>click to see</summary>
<p>

---

Statistical properties of package structure as distributional percentiles in relation to all current CRAN packages
The following terminology is used:
- `loc` = "Lines of Code"
- `fn` = "function"
- `exp`/`not_exp` = exported / not exported

The final measure (`fn_call_network_size`) is the total number of calls between functions (in R), or more abstract relationships between code objects in other languages. Values are flagged as "noteworthy" when they lie in the upper or lower 5th percentile.

|measure              | value| percentile|noteworthy |
|:--------------------|-----:|----------:|:----------|
|files_R              |     4|       23.3|           |
|files_vignettes      |     0|        0.0|TRUE       |
|files_tests          |     2|       64.1|           |
|loc_R                |    10|        0.4|TRUE       |
|loc_tests            |     6|        4.2|TRUE       |
|loc_per_fn_r         |     3|        2.3|TRUE       |
|loc_per_fn_r_not_exp |     3|        4.0|TRUE       |
|loc_per_fn_src       |     4|        1.8|TRUE       |
|loc_per_fn_r         |     3|        2.3|TRUE       |
|loc_per_fn_r_not_exp |     3|        4.0|TRUE       |
|loc_per_fn_src       |     4|        1.8|TRUE       |
|fn_call_network_size |     1|        0.3|TRUE       |

---
</p></details>

### Network visualisation

[Click here](http://127.0.0.1:8000/assets/srr-demo_pkgstats1e2f8c99.html) for interactive network visualisation of calls between objects in package.

**Continuous Integration Badges**

(There do not appear to be any)

### goodpractice results


### R CMD check

R CMD check generated the following check_fail:

1. description_bugreports

### Test Coverage

Package: 0

The following files are not completely covered by tests:

file | coverage
--- | ---
R/test.R | 0%
src/cpptest.cpp | 0%


</p></details>



### srr


- :heavy_check_mark: This package is ready to submit!

[Click here to view output of 'srr_report'](http://127.0.0.1:8000/assets/srr-demo_srr1e2f8c99.html), which can be re-generated locally by running the [`srr_report() function](https://ropenscilabs.github.io/srr/reference/srr_report.html) from within a local clone of the repository.


## Editor-in-Chief Instructions:

Processing may not proceed until the items marked with :heavy_multiplication_x: have been resolved.

**Comment by mpadge** [comment]
@ropensci-review-bot goodtoreview

**Comment by noamross** [comment]
@ropensci-review-bot assign @mpadge as editor

**Comment by mpadge** [comment]
@ropensci-review-bot add @noamross to reviewers

**Comment by mpadge** [comment]
@ropensci-review-bot help

**Comment by mpadge** [comment]
@ropensci-review-bot check package

**Comment by mpadge** [comment]
@ropensci-review-bot goodtoreview

**Comment by mpadge** [comment]
@ropensci-review-bot check package
